name: coffeeapp
description: "Coffee App"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  avatar_plus: ^0.0.5
  google_nav_bar: ^5.0.7
  banner_image: ^1.0.9
  intl: ^0.20.2
  logger: ^2.5.0
  flutter_rating_stars: ^1.1.0
  flutter_native_splash: ^2.4.7
  provider: ^6.1.5
  video_player: ^2.9.5
  package_info_plus: ^8.3.0
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  http: ^1.4.0
  sqflite_common_ffi: ^2.3.5
  path: ^1.9.1
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  flutter_slidable: ^4.0.0
  animate_gradient: ^0.0.3
  lottie: ^3.3.1
  syncfusion_flutter_charts: ^29.2.9
  fl_chart: ^1.0.0
  audioplayers: ^6.5.1
  carousel_slider: ^5.0.0
  badges: ^3.1.2
  flutter_dotenv: ^6.0.0
  google_generative_ai: ^0.4.7
  material_symbols_icons: ^4.2892.0
  flutter_svg: ^2.0.9
  flutter_stripe: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/background_coffee.jpg
    - assets/images/logo.png
    - assets/admin_avatar.png
    - assets/logo.png
    - assets/images/banner/firstbanner.jpg
    - assets/images/banner/secondbanner.jpg
    - assets/images/banner/thirdbanner.jpg
    - assets/images/drink/lemontea.jpg
    - assets/images/drink/product1.png
    - assets/images/drink/product2.png
    - assets/images/drink/product3.png
    - assets/images/drink/product4.png
    - assets/images/drink/product5.png
    - assets/images/drink/category1.png
    - assets/images/drink/category2.jpg
    - assets/images/drink/category3.png
    - assets/images/drink/category4.png
    - assets/images/drink/category5.png
    - assets/images/drink/category6.jpg
    - assets/images/drink/category7.jpg
    - assets/images/drink/PlaceholderProductImage.jpg
    - assets/images/drink/user.png
    - assets/video/PhiNomcoffeeIntro.mp4
    - assets/background/login_hero.jpg
    - assets/images/rank/r0.png
    - assets/images/rank/r1.png
    - assets/images/rank/r2.png
    - assets/images/rank/r3.png
    - assets/images/rank/r4.png
    - assets/images/rank/r5.png
    - assets/background/coffeeproductbackground.jpg
    - assets/video/icons8-add-shopping-cart.gif
    - assets/video/icons8-shopping-cart.gif
    - assets/video/CoffeeFavourite.json
    - assets/video/CoffeeRecommended.json
    - assets/background/CoffeeTitle.json
    - assets/background/loading.json
    - assets/background/coffee_pour.json
    - assets/audio/coffee_pour_sound.mp3
    - assets/icons/apple.svg
    - assets/icons/google.svg
fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Regular.ttf
      - asset: assets/fonts/Poppins-SemiBold.ttf
        weight: 600
  - family: Inter
    fonts:
      - asset: assets/fonts/Inter-Regular.ttf
      - asset: assets/fonts/Inter-Medium.ttf

